config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'deal-investment-criteria/add'

  resources :proposals

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :headquarters, presence: true
  validates :operations, presence: true
  validates :sector, presence: true
  validates :type_of_acquirers, presence: true
  validates :potential_stake_offered, presence: true
  validates :reason_for_sale, presence: true
  validates :revenue, presence: true
  validates :ebitda, presence: true
  validates :net_income, presence: true
  validates :your_role, presence: true
  validates :exclusive_mandate, presence: true
  validates :social_impact, presence: true
  validates :additional_description, presence: true

  PROPOSAL_TYPES = ["corporate-acquirer-strategic-buyer", "corporate-seller-exit-buyout-mergers-acquisitions"]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :proposals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    @proposals = Proposal.all
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    @proposal = Proposal.new
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def create
    @proposal = current_user.proposals.new(proposal_params)
    if @proposal.save
      redirect_to @proposal
    else
      render 'new'
    end
  end

  def update
    @proposal = Proposal.find(params[:id])

    if @proposal.update(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end


  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    redirect_to proposals_path
  end

  private
    def proposal_params
      params.require(:proposal).permit(:title, :headquarters, :reason_for_sale, :revenue, :ebitda, :net_income, :social_impact, :additional_description, operations: [], sector: [], potential_stake_offered: [], type_of_acquirers: [], your_role: [], exclusive_mandate: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/home/index.html.erb
<h1>Welcome,  <%= current_user.email %></h1>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
  </div>
</div>
<%= link_to 'Proposals', controller: 'proposals' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Horizonsplatform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="/proposals/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Proposals
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/proposals/new/">Add Proposal</a>
          <a class="dropdown-item" href="/proposals/">All Proposals</a>
          <a class="dropdown-item" href="/proposals/">My Proposals</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'dropdown-item' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <% end %>

      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/proposals/_form.html.erb
<%= simple_form_for @proposal, wrapper: :input_group, validate: true do |f| %>
  <%= f.error_notification %>

  <div class='label'>Please give your proposal a name</div>
  <%= f.input :title, input_html: { :size => 10, "data-tooltip" => true, :class => "dashboard-tooltip", data: { content: 'this is the message', placement: 'top', trigger: 'hover' } }, label: false, error: 'Mandatory' %>
  <br>
  <h6>ABOUT THE SELLER</h6>
  <br>
  <div class='label'>Headquarters</div>
  <%= f.country_select :headquarters, { include_blank: true }, { class: 'chosen-select'} %>
  <br>
  <br>
  <div class='label'>Operations</div>
  <%= f.country_select :operations, { include_blank: true }, { class: 'chosen-select', multiple: 'multiple'} %>
  <br>
  <br>
  <div class='label'>Sector</div>
  <%= f.input :sector, collection: ['Energy',
                                    'Materials',
                                    'Capital Goods',
                                    'Commercial & Professional Services',
                                    'Transportation',
                                    'Automobiles & Components',
                                    'Consumer Durables &amp; Apparel',
                                    'Consumer Services',
                                    'Media',
                                    'Retailing',
                                    'Food & Staples Retailing',
                                    'Food, Beverage & Tobacco',
                                    'Household & Personal Products',
                                    'Health Care Equipment & Services',
                                    'Pharmaceuticals, Biotechnology & Life Sciences',
                                    'Banks',
                                    'Diversified Financials',
                                    'Insurance',
                                    'Real Estate',
                                    'Software & Services',
                                    'Technology Hardware & Equipment',
                                    'Semiconductors & Semiconductor Equipment',
                                    'Telecommunication Services'
                                    ],
                        input_html: { class: 'chosen-select', multiple: 'multiple' },
                        label: false,
                        error: 'Mandatory'%>
  <br>
  <br>
  <h6>TRANSACTION</h6>
  <br>
  <div class='label'>Type of acquirers</div>
  <%= f.input :type_of_acquirers,
             collection: ['Strategic',
                          'Financial'],
             input_html: { class: 'chosen-select', multiple: 'multiple' },
             label: false,
             error: 'Mandatory'%>
  <br>
  <div class='label'>Potential stake offered</div>
  <%= f.input :potential_stake_offered,
             collection: ['Less than 50%',
                          'More than 50%',
                          '100%'],
             input_html: { class: 'chosen-select', multiple: 'multiple' },
             label: false,
             error: 'Mandatory'%>
<br>
<div class='label'>Reason for Sale</div>
<%= f.input :reason_for_sale,
           as: :text,
           label: false,
           error: 'Mandatory'%>
<br>
<h6>FINANCIAL DETAILS</h6>
<br>
<div class='label'>Revenue (Million US$)</div>
<%= f.input :revenue, prepend: "US$", append: "M", label: false  %>
<br>
<div class='label'>EBITDA (Million US$)</div>
<%= f.input :ebitda, prepend: "US$", append: "M", label: false  %>
<br>
<div class='label'>Net Income (Million US$)</div>
<%= f.input :net_income, prepend: "US$", append: "M", label: false  %>

<h6>ABOUT YOU</h6>
<div class='label'>Your role in the transaction</div>
<%= f.input :your_role,
           collection: ['Advisor',
                        'Direct Party',
                        '100%'],
           input_html: { class: 'chosen-select', multiple: 'multiple' },
           label: false,
           error: 'Mandatory'%>

<div class='label'>Do you have an Exclusive mandate </div>
<%= f.input :exclusive_mandate,
           collection: ['Yes',
                        'No'],
           input_html: { class: 'chosen-select', multiple: 'multiple' },
           label: false,
           error: 'Mandatory'%>

<div class='label'>Is this a Social Impact deal? </div>
<%= f.input :social_impact, as: :radio_buttons %>

<div class='label'>Additional description</div>
<%= f.input :additional_description,
           as: :text,
           label: false,
           error: 'Mandatory'%>
<br>

  <%= f.submit 'Submit' %>
<% end %>

app/views/proposals/edit.html.erb
<h1>Edit proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New proposal', new_proposal_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>


  <% @proposals.each do |proposal| %>
    <tr>
      <td><%= proposal.title %></td>
      <td><%= link_to 'Show', proposal_path(proposal) %></td>
      <% if user_signed_in? && current_user.id == proposal.user_id %>
      <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
      <td><%= link_to 'Destroy', proposal_path(proposal),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/proposals/new.html.erb
<div class="container">
  <div class="container ">

  </div>
<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

</div>

app/views/proposals/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @proposal.title %>
</p>

<p>
  <strong>Headquarters:</strong>
  <%= @proposal.headquarters %>
</p>

<p>
  <strong>Operations:</strong>
  <%= @proposal.operations %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @proposal.sector %>
</p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %>
<%= link_to 'Back', proposals_path %>